CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID UUID PRIMARY KEY,
    NUMBER VARCHAR(20) UNIQUE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_ACCOUNT_NUMBER ON ACCOUNT(NUMBER);

GRANT SELECT, INSERT, UPDATE, DELETE ON ACCOUNT TO "payment-producer-app";
