spring:
  application:
    name: payment-producer-api
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/payments_db
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: payment
      maximum-pool-size: 10
  jpa:
   show-sql: true
   properties:
    hibernate:
     format_sql: true
     highlight_sql: true
  data:
   redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    connect-timeout: 5000ms
    lettuce:
     pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1ms

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/payments_db
    schemas: payment
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
